var searchData=
[
  ['ramsetecommand_0',['RamseteCommand',['../classfrc2_1_1_ramsete_command.html',1,'frc2']]],
  ['ramsetecontroller_1',['RamseteController',['../classfrc_1_1_ramsete_controller.html',1,'frc']]],
  ['range_5fformat_5fkind_2',['range_format_kind',['../structrange__format__kind.html',1,'']]],
  ['range_5fformat_5fkind_5f_3',['range_format_kind_',['../structdetail_1_1range__format__kind__.html',1,'detail']]],
  ['range_5fformatter_4',['range_formatter',['../structrange__formatter.html',1,'']]],
  ['range_5fformatter_3c_20detail_3a_3auncvref_5ftype_3c_20range_5ftype_20_3e_2c_20char_20_3e_5',['range_formatter&lt; detail::uncvref_type&lt; range_type &gt;, Char &gt;',['../structrange__formatter.html',1,'']]],
  ['range_5fformatter_3c_20t_2c_20char_2c_20enable_5fif_5ft_3c_20conjunction_3c_20std_3a_3ais_5fsame_3c_20t_2c_20remove_5fcvref_5ft_3c_20t_20_3e_20_3e_2c_20is_5fformattable_3c_20t_2c_20char_20_3e_20_3e_3a_3avalue_20_3e_20_3e_6',['range_formatter&lt; T, Char, enable_if_t&lt; conjunction&lt; std::is_same&lt; T, remove_cvref_t&lt; T &gt; &gt;, is_formattable&lt; T, Char &gt; &gt;::value &gt; &gt;',['../structrange__formatter_3_01_t_00_01_char_00_01enable__if__t_3_01conjunction_3_01std_1_1is__same_edf46378efa9da3f820c5aa7a483895e.html',1,'']]],
  ['raw_5ffd_5fistream_7',['raw_fd_istream',['../classwpi_1_1raw__fd__istream.html',1,'wpi']]],
  ['raw_5ffd_5fostream_8',['raw_fd_ostream',['../classwpi_1_1raw__fd__ostream.html',1,'wpi']]],
  ['raw_5ffd_5fstream_9',['raw_fd_stream',['../classwpi_1_1raw__fd__stream.html',1,'wpi']]],
  ['raw_5fistream_10',['raw_istream',['../classwpi_1_1raw__istream.html',1,'wpi']]],
  ['raw_5fmem_5fistream_11',['raw_mem_istream',['../classwpi_1_1raw__mem__istream.html',1,'wpi']]],
  ['raw_5fnull_5fostream_12',['raw_null_ostream',['../classwpi_1_1raw__null__ostream.html',1,'wpi']]],
  ['raw_5fos_5fostream_13',['raw_os_ostream',['../classwpi_1_1raw__os__ostream.html',1,'wpi']]],
  ['raw_5fostream_14',['raw_ostream',['../classwpi_1_1raw__ostream.html',1,'wpi']]],
  ['raw_5fostream_5fadapter_15',['raw_ostream_adapter',['../classdetail_1_1raw__ostream__adapter.html',1,'detail']]],
  ['raw_5fpwrite_5fstream_16',['raw_pwrite_stream',['../classwpi_1_1raw__pwrite__stream.html',1,'wpi']]],
  ['raw_5fsocket_5fistream_17',['raw_socket_istream',['../classwpi_1_1raw__socket__istream.html',1,'wpi']]],
  ['raw_5fsocket_5fostream_18',['raw_socket_ostream',['../classwpi_1_1raw__socket__ostream.html',1,'wpi']]],
  ['raw_5fstring_5fostream_19',['raw_string_ostream',['../classwpi_1_1raw__string__ostream.html',1,'wpi']]],
  ['raw_5fsvector_5fostream_20',['raw_svector_ostream',['../classwpi_1_1raw__svector__ostream.html',1,'wpi']]],
  ['raw_5fusvector_5fostream_21',['raw_usvector_ostream',['../classwpi_1_1raw__usvector__ostream.html',1,'wpi']]],
  ['raw_5fuv_5fostream_22',['raw_uv_ostream',['../classwpi_1_1raw__uv__ostream.html',1,'wpi']]],
  ['raw_5fuvector_5fostream_23',['raw_uvector_ostream',['../classwpi_1_1raw__uvector__ostream.html',1,'wpi']]],
  ['raw_5fvector_5fostream_24',['raw_vector_ostream',['../classwpi_1_1raw__vector__ostream.html',1,'wpi']]],
  ['rawentry_25',['RawEntry',['../classnt_1_1_raw_entry.html',1,'nt']]],
  ['rawevent_26',['RawEvent',['../structcs_1_1_raw_event.html',1,'cs']]],
  ['rawframe_27',['RawFrame',['../structwpi_1_1_raw_frame.html',1,'wpi']]],
  ['rawlogentry_28',['RawLogEntry',['../classwpi_1_1log_1_1_raw_log_entry.html',1,'wpi::log']]],
  ['rawpublisher_29',['RawPublisher',['../classnt_1_1_raw_publisher.html',1,'nt']]],
  ['rawsink_30',['RawSink',['../classcs_1_1_raw_sink.html',1,'cs']]],
  ['rawsource_31',['RawSource',['../classcs_1_1_raw_source.html',1,'cs']]],
  ['rawsubscriber_32',['RawSubscriber',['../classnt_1_1_raw_subscriber.html',1,'nt']]],
  ['rawtopic_33',['RawTopic',['../classnt_1_1_raw_topic.html',1,'nt']]],
  ['rebind_34',['rebind',['../structwpi_1_1memory_1_1std__allocator_1_1rebind.html',1,'wpi::memory::std_allocator']]],
  ['rebind_5fblock_5fallocator_35',['rebind_block_allocator',['../structwpi_1_1memory_1_1detail_1_1rebind__block__allocator.html',1,'wpi::memory::detail']]],
  ['rebind_5fblock_5fallocator_3c_20rawallocator_3c_20args_2e_2e_2e_20_3e_2c_20otherblockallocator_20_3e_36',['rebind_block_allocator&lt; RawAllocator&lt; Args... &gt;, OtherBlockAllocator &gt;',['../structwpi_1_1memory_1_1detail_1_1rebind__block__allocator_3_01_raw_allocator_3_01_args_8_8_8_01_600b305b159ae64535881b7c55b7ad7d.html',1,'wpi::memory::detail']]],
  ['recordingcontroller_37',['RecordingController',['../classfrc_1_1detail_1_1_recording_controller.html',1,'frc::detail']]],
  ['rectangle2d_38',['Rectangle2d',['../classfrc_1_1_rectangle2d.html',1,'frc']]],
  ['rectangularregionconstraint_39',['RectangularRegionConstraint',['../classfrc_1_1_rectangular_region_constraint.html',1,'frc']]],
  ['recursive_5fspinlock1_40',['recursive_spinlock1',['../classwpi_1_1recursive__spinlock1.html',1,'wpi']]],
  ['recursive_5fspinlock2_41',['recursive_spinlock2',['../classwpi_1_1recursive__spinlock2.html',1,'wpi']]],
  ['ref_42',['ref',['../structwpi_1_1support_1_1detail_1_1packed__endian__specific__integral_1_1ref.html',1,'wpi::support::detail::packed_endian_specific_integral']]],
  ['reference_5fshared_43',['reference_shared',['../structwpi_1_1memory_1_1detail_1_1reference__shared.html',1,'wpi::memory::detail']]],
  ['reference_5fstateful_44',['reference_stateful',['../structwpi_1_1memory_1_1detail_1_1reference__stateful.html',1,'wpi::memory::detail']]],
  ['reference_5fstateless_45',['reference_stateless',['../structwpi_1_1memory_1_1detail_1_1reference__stateless.html',1,'wpi::memory::detail']]],
  ['reference_5fstorage_46',['reference_storage',['../classwpi_1_1memory_1_1reference__storage.html',1,'wpi::memory']]],
  ['reference_5fstorage_3c_20any_5fallocator_20_3e_47',['reference_storage&lt; any_allocator &gt;',['../classwpi_1_1memory_1_1reference__storage_3_01any__allocator_01_4.html',1,'wpi::memory']]],
  ['reference_5fstorage_5fimpl_48',['reference_storage_impl',['../classwpi_1_1memory_1_1detail_1_1reference__storage__impl.html',1,'wpi::memory::detail']]],
  ['reference_5fstorage_5fimpl_3c_20allocator_5ftraits_3c_20rawallocator_20_3e_3a_3aallocator_5ftype_2c_20decltype_28detail_3a_3areference_5ftype_28allocator_5ftraits_3c_20rawallocator_20_3e_3a_3ais_5fstateful_7b_7d_2c_20is_5fshared_5fallocator_3c_20rawallocator_20_3e_7b_7d_29_29_3e_49',['reference_storage_impl&lt; allocator_traits&lt; RawAllocator &gt;::allocator_type, decltype(detail::reference_type(allocator_traits&lt; RawAllocator &gt;::is_stateful{}, is_shared_allocator&lt; RawAllocator &gt;{}))&gt;',['../classwpi_1_1memory_1_1detail_1_1reference__storage__impl.html',1,'wpi::memory::detail']]],
  ['reference_5fstorage_5fimpl_3c_20rawallocator_2c_20reference_5fshared_20_3e_50',['reference_storage_impl&lt; RawAllocator, reference_shared &gt;',['../classwpi_1_1memory_1_1detail_1_1reference__storage__impl_3_01_raw_allocator_00_01reference__shared_01_4.html',1,'wpi::memory::detail']]],
  ['reference_5fstorage_5fimpl_3c_20rawallocator_2c_20reference_5fstateful_20_3e_51',['reference_storage_impl&lt; RawAllocator, reference_stateful &gt;',['../classwpi_1_1memory_1_1detail_1_1reference__storage__impl_3_01_raw_allocator_00_01reference__stateful_01_4.html',1,'wpi::memory::detail']]],
  ['reference_5fstorage_5fimpl_3c_20rawallocator_2c_20reference_5fstateless_20_3e_52',['reference_storage_impl&lt; RawAllocator, reference_stateless &gt;',['../classwpi_1_1memory_1_1detail_1_1reference__storage__impl_3_01_raw_allocator_00_01reference__stateless_01_4.html',1,'wpi::memory::detail']]],
  ['referenceproxy_53',['ReferenceProxy',['../classwpi_1_1iterator__facade__base_1_1_reference_proxy.html',1,'wpi::iterator_facade_base']]],
  ['relay_54',['Relay',['../classfrc_1_1_relay.html',1,'frc']]],
  ['relaydoao_55',['RelayDOAO',['../struct_h_a_l___h_m_b_data_1_1_relay_d_o_a_o.html',1,'HAL_HMBData']]],
  ['relaysim_56',['RelaySim',['../classfrc_1_1sim_1_1_relay_sim.html',1,'frc::sim']]],
  ['remove_5fcvref_57',['remove_cvref',['../structwpi_1_1remove__cvref.html',1,'wpi']]],
  ['repeatcommand_58',['RepeatCommand',['../classfrc2_1_1_repeat_command.html',1,'frc2']]],
  ['request_59',['Request',['../classwpi_1_1uv_1_1_request.html',1,'wpi::uv']]],
  ['requestimpl_60',['RequestImpl',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20connectreq_2c_20uv_5fconnect_5ft_20_3e_61',['RequestImpl&lt; ConnectReq, uv_connect_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20getaddrinforeq_2c_20uv_5fgetaddrinfo_5ft_20_3e_62',['RequestImpl&lt; GetAddrInfoReq, uv_getaddrinfo_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20getnameinforeq_2c_20uv_5fgetnameinfo_5ft_20_3e_63',['RequestImpl&lt; GetNameInfoReq, uv_getnameinfo_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20shutdownreq_2c_20uv_5fshutdown_5ft_20_3e_64',['RequestImpl&lt; ShutdownReq, uv_shutdown_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20udpsendreq_2c_20uv_5fudp_5fsend_5ft_20_3e_65',['RequestImpl&lt; UdpSendReq, uv_udp_send_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20workreq_2c_20uv_5fwork_5ft_20_3e_66',['RequestImpl&lt; WorkReq, uv_work_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20writereq_2c_20uv_5fwrite_5ft_20_3e_67',['RequestImpl&lt; WriteReq, uv_write_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requirements_68',['Requirements',['../classfrc2_1_1_requirements.html',1,'frc2']]],
  ['resource_69',['Resource',['../classfrc_1_1_resource.html',1,'frc']]],
  ['results_70',['Results',['../classfrc_1_1_april_tag_detector_1_1_results.html',1,'frc::AprilTagDetector']]],
  ['revphsim_71',['REVPHSim',['../classfrc_1_1sim_1_1_r_e_v_p_h_sim.html',1,'frc::sim']]],
  ['rgb_72',['rgb',['../structrgb.html',1,'']]],
  ['roboriosim_73',['RoboRioSim',['../classfrc_1_1sim_1_1_robo_rio_sim.html',1,'frc::sim']]],
  ['robotbase_74',['RobotBase',['../classfrc_1_1_robot_base.html',1,'frc']]],
  ['robotcontroller_75',['RobotController',['../classfrc_1_1_robot_controller.html',1,'frc']]],
  ['robotdrivebase_76',['RobotDriveBase',['../classfrc_1_1_robot_drive_base.html',1,'frc']]],
  ['robotmodetriggers_77',['RobotModeTriggers',['../classfrc2_1_1_robot_mode_triggers.html',1,'frc2']]],
  ['robotstate_78',['RobotState',['../classfrc_1_1_robot_state.html',1,'frc']]],
  ['romigyro_79',['RomiGyro',['../classfrc_1_1_romi_gyro.html',1,'frc']]],
  ['romimotor_80',['RomiMotor',['../classfrc_1_1_romi_motor.html',1,'frc']]],
  ['rotated_5fspan_81',['rotated_span',['../classwpi_1_1rotated__span.html',1,'wpi']]],
  ['rotation2d_82',['Rotation2d',['../classfrc_1_1_rotation2d.html',1,'frc']]],
  ['rotation3d_83',['Rotation3d',['../classfrc_1_1_rotation3d.html',1,'frc']]],
  ['runcommand_84',['RunCommand',['../classfrc2_1_1_run_command.html',1,'frc2']]],
  ['runtime_5fformat_5fstring_85',['runtime_format_string',['../structruntime__format__string.html',1,'']]],
  ['runtimeerror_86',['RuntimeError',['../classfrc_1_1_runtime_error.html',1,'frc']]]
];
