var searchData=
[
  ['ubitint_0',['ubitint',['../structdetail_1_1ubitint.html',1,'detail']]],
  ['udl_5farg_1',['udl_arg',['../structdetail_1_1udl__arg.html',1,'detail']]],
  ['udp_2',['Udp',['../classwpi_1_1uv_1_1_udp.html',1,'wpi::uv']]],
  ['udpclient_3',['UDPClient',['../classwpi_1_1_u_d_p_client.html',1,'wpi']]],
  ['udpsendreq_4',['UdpSendReq',['../classwpi_1_1uv_1_1_udp_send_req.html',1,'wpi::uv']]],
  ['uidvector_5',['UidVector',['../classwpi_1_1_uid_vector.html',1,'wpi']]],
  ['uidvector_3c_20listenerdata_2c_2064_20_3e_6',['UidVector&lt; ListenerData, 64 &gt;',['../classwpi_1_1_uid_vector.html',1,'wpi']]],
  ['uidvector_3c_20std_3a_3ashared_5fptr_3c_20wpi_3a_3acallbackthread_3a_3apoller_20_3e_2c_2064_20_3e_7',['UidVector&lt; std::shared_ptr&lt; wpi::CallbackThread::Poller &gt;, 64 &gt;',['../classwpi_1_1_uid_vector.html',1,'wpi']]],
  ['uidvectoriterator_8',['UidVectorIterator',['../classwpi_1_1impl_1_1_uid_vector_iterator.html',1,'wpi::impl']]],
  ['uint128_5ffallback_9',['uint128_fallback',['../classdetail_1_1uint128__fallback.html',1,'detail']]],
  ['uleb128reader_10',['Uleb128Reader',['../classwpi_1_1_uleb128_reader.html',1,'wpi']]],
  ['ultrasonic_11',['Ultrasonic',['../classfrc_1_1_ultrasonic.html',1,'frc']]],
  ['ultrasonicsim_12',['UltrasonicSim',['../classfrc_1_1sim_1_1_ultrasonic_sim.html',1,'frc::sim']]],
  ['unexpect_5ft_13',['unexpect_t',['../structwpi_1_1unexpect__t.html',1,'wpi']]],
  ['unexpected_14',['unexpected',['../classwpi_1_1unexpected.html',1,'wpi']]],
  ['unionfind_15',['unionfind',['../structunionfind.html',1,'']]],
  ['unique_5fbase_5fptr_16',['unique_base_ptr',['../classwpi_1_1memory_1_1unique__base__ptr.html',1,'wpi::memory']]],
  ['unique_5ffunction_17',['unique_function',['../classwpi_1_1unique__function.html',1,'wpi']]],
  ['unique_5ffunction_3c_20frc2_3a_3acommand_20_2a_28_29_3e_18',['unique_function&lt; frc2::Command *()&gt;',['../classwpi_1_1unique__function.html',1,'wpi']]],
  ['unique_5ffunction_3c_20frc2_3a_3acommandptr_28_29_3e_19',['unique_function&lt; frc2::CommandPtr()&gt;',['../classwpi_1_1unique__function.html',1,'wpi']]],
  ['unique_5ffunction_3c_20r_28p_2e_2e_2e_29_20const_20_3e_20',['unique_function&lt; R(P...) const &gt;',['../classwpi_1_1unique__function_3_01_r_07_p_8_8_8_08_01const_01_4.html',1,'wpi']]],
  ['unique_5ffunction_3c_20r_28p_2e_2e_2e_29_3e_21',['unique_function&lt; R(P...)&gt;',['../classwpi_1_1unique__function_3_01_r_07_p_8_8_8_08_4.html',1,'wpi']]],
  ['unique_5fptr_22',['unique_ptr',['../classwpi_1_1memory_1_1unique__ptr.html',1,'wpi::memory']]],
  ['uniquefunctionbase_23',['UniqueFunctionBase',['../classwpi_1_1detail_1_1_unique_function_base.html',1,'wpi::detail']]],
  ['uniquefunctionbase_3c_20r_2c_20p_2e_2e_2e_20_3e_24',['UniqueFunctionBase&lt; R, P... &gt;',['../classwpi_1_1detail_1_1_unique_function_base.html',1,'wpi::detail']]],
  ['uniqueptrcast_25',['UniquePtrCast',['../structwpi_1_1_unique_ptr_cast.html',1,'wpi']]],
  ['unit_26',['unit',['../structunits_1_1unit.html',1,'units']]],
  ['unit_5ft_27',['unit_t',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20acceleration_20_3e_28',['unit_t&lt; Acceleration &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20b_5funit_20_3e_29',['unit_t&lt; b_unit &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20distance_20_3e_30',['unit_t&lt; Distance &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20input_20_3e_31',['unit_t&lt; Input &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20ka_5funit_20_3e_32',['unit_t&lt; ka_unit &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20kv_5funit_20_3e_33',['unit_t&lt; kv_unit &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20rate_20_3e_34',['unit_t&lt; Rate &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20unit_20_3e_35',['unit_t&lt; Unit &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3acompound_5funit_3c_20acceleration_2c_20units_3a_3ainverse_3c_20input_20_3e_20_3e_20_3e_36',['unit_t&lt; units::compound_unit&lt; Acceleration, units::inverse&lt; Input &gt; &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3acompound_5funit_3c_20units_3a_3anewton_5fmeters_2c_20units_3a_3ainverse_3c_20units_3a_3aampere_20_3e_20_3e_20_3e_37',['unit_t&lt; units::compound_unit&lt; units::newton_meters, units::inverse&lt; units::ampere &gt; &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3acompound_5funit_3c_20units_3a_3aradians_2c_20units_3a_3ainverse_3c_20units_3a_3ameters_20_3e_20_3e_20_3e_38',['unit_t&lt; units::compound_unit&lt; units::radians, units::inverse&lt; units::meters &gt; &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3acompound_5funit_3c_20units_3a_3aradians_5fper_5fsecond_2c_20units_3a_3ainverse_3c_20units_3a_3avolt_20_3e_20_3e_20_3e_39',['unit_t&lt; units::compound_unit&lt; units::radians_per_second, units::inverse&lt; units::volt &gt; &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3acompound_5funit_3c_20units_3a_3avolt_2c_20units_3a_3ainverse_3c_20units_3a_3asecond_20_3e_20_3e_20_3e_40',['unit_t&lt; units::compound_unit&lt; units::volt, units::inverse&lt; units::second &gt; &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3ainverse_3c_20units_3a_3aseconds_20_3e_20_3e_41',['unit_t&lt; units::inverse&lt; units::seconds &gt; &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20units_3a_3aradian_20_3e_42',['unit_t&lt; units::radian &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20velocity_20_3e_43',['unit_t&lt; Velocity &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5ft_3c_20zeta_5funit_20_3e_44',['unit_t&lt; zeta_unit &gt;',['../classunits_1_1unit__t.html',1,'units']]],
  ['unit_5fvalue_5fadd_45',['unit_value_add',['../structunits_1_1unit__value__add.html',1,'units']]],
  ['unit_5fvalue_5fdivide_46',['unit_value_divide',['../structunits_1_1unit__value__divide.html',1,'units']]],
  ['unit_5fvalue_5fmultiply_47',['unit_value_multiply',['../structunits_1_1unit__value__multiply.html',1,'units']]],
  ['unit_5fvalue_5fpower_48',['unit_value_power',['../structunits_1_1unit__value__power.html',1,'units']]],
  ['unit_5fvalue_5fsqrt_49',['unit_value_sqrt',['../structunits_1_1unit__value__sqrt.html',1,'units']]],
  ['unit_5fvalue_5fsubtract_50',['unit_value_subtract',['../structunits_1_1unit__value__subtract.html',1,'units']]],
  ['unit_5fvalue_5ft_51',['unit_value_t',['../structunits_1_1unit__value__t.html',1,'units']]],
  ['unitentry_52',['UnitEntry',['../classnt_1_1_unit_entry.html',1,'nt']]],
  ['unitpublisher_53',['UnitPublisher',['../classnt_1_1_unit_publisher.html',1,'nt']]],
  ['unitsubscriber_54',['UnitSubscriber',['../classnt_1_1_unit_subscriber.html',1,'nt']]],
  ['unittopic_55',['UnitTopic',['../classnt_1_1_unit_topic.html',1,'nt']]],
  ['unlimitedhandleresource_56',['UnlimitedHandleResource',['../classhal_1_1_unlimited_handle_resource.html',1,'hal']]],
  ['unordered_5fmap_57',['unordered_map',['../classwpi_1_1memory_1_1unordered__map.html',1,'wpi::memory']]],
  ['unordered_5fmap_5fnode_5fsize_58',['unordered_map_node_size',['../structwpi_1_1memory_1_1unordered__map__node__size.html',1,'wpi::memory']]],
  ['unordered_5fmap_5fscoped_5falloc_59',['unordered_map_scoped_alloc',['../classwpi_1_1memory_1_1unordered__map__scoped__alloc.html',1,'wpi::memory']]],
  ['unordered_5fmultimap_60',['unordered_multimap',['../classwpi_1_1memory_1_1unordered__multimap.html',1,'wpi::memory']]],
  ['unordered_5fmultimap_5fnode_5fsize_61',['unordered_multimap_node_size',['../structwpi_1_1memory_1_1unordered__multimap__node__size.html',1,'wpi::memory']]],
  ['unordered_5fmultimap_5fscoped_5falloc_62',['unordered_multimap_scoped_alloc',['../classwpi_1_1memory_1_1unordered__multimap__scoped__alloc.html',1,'wpi::memory']]],
  ['unordered_5fmultiset_63',['unordered_multiset',['../classwpi_1_1memory_1_1unordered__multiset.html',1,'wpi::memory']]],
  ['unordered_5fmultiset_5fnode_5fsize_64',['unordered_multiset_node_size',['../structwpi_1_1memory_1_1unordered__multiset__node__size.html',1,'wpi::memory']]],
  ['unordered_5fmultiset_5fscoped_5falloc_65',['unordered_multiset_scoped_alloc',['../classwpi_1_1memory_1_1unordered__multiset__scoped__alloc.html',1,'wpi::memory']]],
  ['unordered_5fset_66',['unordered_set',['../classwpi_1_1memory_1_1unordered__set.html',1,'wpi::memory']]],
  ['unordered_5fset_5fnode_5fsize_67',['unordered_set_node_size',['../structwpi_1_1memory_1_1unordered__set__node__size.html',1,'wpi::memory']]],
  ['unordered_5fset_5fscoped_5falloc_68',['unordered_set_scoped_alloc',['../classwpi_1_1memory_1_1unordered__set__scoped__alloc.html',1,'wpi::memory']]],
  ['unpackcallback_69',['UnpackCallback',['../classwpi_1_1_unpack_callback.html',1,'wpi']]],
  ['unscentedkalmanfilter_70',['UnscentedKalmanFilter',['../classfrc_1_1_unscented_kalman_filter.html',1,'frc']]],
  ['updowncounter_71',['UpDownCounter',['../classfrc_1_1_up_down_counter.html',1,'frc']]],
  ['urlparser_72',['UrlParser',['../classwpi_1_1_url_parser.html',1,'wpi']]],
  ['usbcamera_73',['UsbCamera',['../classcs_1_1_usb_camera.html',1,'cs']]],
  ['usbcamerainfo_74',['UsbCameraInfo',['../structcs_1_1_usb_camera_info.html',1,'cs']]],
  ['use_5fformat_5fas_75',['use_format_as',['../structdetail_1_1use__format__as.html',1,'detail']]],
  ['use_5fformat_5fas_3c_20t_2c_20bool_5fconstant_3c_20std_3a_3ais_5farithmetic_3c_20format_5fas_5fresult_3c_20t_20_3e_20_3e_3a_3avalue_20_3e_20_3e_76',['use_format_as&lt; T, bool_constant&lt; std::is_arithmetic&lt; format_as_result&lt; T &gt; &gt;::value &gt; &gt;',['../structdetail_1_1use__format__as_3_01_t_00_01bool__constant_3_01std_1_1is__arithmetic_3_01format_c5abc3514695b624bf9b94cf4b793f5e.html',1,'detail']]],
  ['use_5fformat_5fas_5fmember_77',['use_format_as_member',['../structdetail_1_1use__format__as__member.html',1,'detail']]],
  ['use_5fformat_5fas_5fmember_3c_20t_2c_20bool_5fconstant_3c_20std_3a_3ais_5farithmetic_3c_20format_5fas_5fmember_5fresult_3c_20t_20_3e_20_3e_3a_3avalue_20_3e_20_3e_78',['use_format_as_member&lt; T, bool_constant&lt; std::is_arithmetic&lt; format_as_member_result&lt; T &gt; &gt;::value &gt; &gt;',['../structdetail_1_1use__format__as__member_3_01_t_00_01bool__constant_3_01std_1_1is__arithmetic_3_0cd3fac984a01ae215ebffbc5fd232617.html',1,'detail']]],
  ['utc_5fclock_79',['utc_clock',['../structdetail_1_1utc__clock.html',1,'detail']]],
  ['utcclock_80',['UtcClock',['../classwpi_1_1sys_1_1_utc_clock.html',1,'wpi::sys']]],
  ['utf8_5fto_5futf16_81',['utf8_to_utf16',['../classdetail_1_1utf8__to__utf16.html',1,'detail']]],
  ['uv_5f_5fdirent_5fs_82',['uv__dirent_s',['../structuv____dirent__s.html',1,'']]],
  ['uv_5f_5fio_5fs_83',['uv__io_s',['../structuv____io__s.html',1,'']]],
  ['uv_5f_5fqueue_84',['uv__queue',['../structuv____queue.html',1,'']]],
  ['uv_5f_5fwork_85',['uv__work',['../structuv____work.html',1,'']]],
  ['uv_5fany_5fhandle_86',['uv_any_handle',['../unionuv__any__handle.html',1,'']]],
  ['uv_5fany_5freq_87',['uv_any_req',['../unionuv__any__req.html',1,'']]],
  ['uv_5fasync_5fs_88',['uv_async_s',['../structuv__async__s.html',1,'']]],
  ['uv_5fbarrier_5ft_89',['uv_barrier_t',['../structuv__barrier__t.html',1,'']]],
  ['uv_5fbuf_5ft_90',['uv_buf_t',['../structuv__buf__t.html',1,'']]],
  ['uv_5fcheck_5fs_91',['uv_check_s',['../structuv__check__s.html',1,'']]],
  ['uv_5fcond_5ft_92',['uv_cond_t',['../unionuv__cond__t.html',1,'']]],
  ['uv_5fconnect_5fs_93',['uv_connect_s',['../structuv__connect__s.html',1,'']]],
  ['uv_5fcpu_5finfo_5fs_94',['uv_cpu_info_s',['../structuv__cpu__info__s.html',1,'']]],
  ['uv_5fcpu_5ftimes_5fs_95',['uv_cpu_times_s',['../structuv__cpu__times__s.html',1,'']]],
  ['uv_5fdir_5fs_96',['uv_dir_s',['../structuv__dir__s.html',1,'']]],
  ['uv_5fdirent_5fs_97',['uv_dirent_s',['../structuv__dirent__s.html',1,'']]],
  ['uv_5fenv_5fitem_5fs_98',['uv_env_item_s',['../structuv__env__item__s.html',1,'']]],
  ['uv_5ffs_5fevent_5fs_99',['uv_fs_event_s',['../structuv__fs__event__s.html',1,'']]],
  ['uv_5ffs_5fpoll_5fs_100',['uv_fs_poll_s',['../structuv__fs__poll__s.html',1,'']]],
  ['uv_5ffs_5fs_101',['uv_fs_s',['../structuv__fs__s.html',1,'']]],
  ['uv_5fgetaddrinfo_5fs_102',['uv_getaddrinfo_s',['../structuv__getaddrinfo__s.html',1,'']]],
  ['uv_5fgetnameinfo_5fs_103',['uv_getnameinfo_s',['../structuv__getnameinfo__s.html',1,'']]],
  ['uv_5fgroup_5fs_104',['uv_group_s',['../structuv__group__s.html',1,'']]],
  ['uv_5fhandle_5fs_105',['uv_handle_s',['../structuv__handle__s.html',1,'']]],
  ['uv_5fidle_5fs_106',['uv_idle_s',['../structuv__idle__s.html',1,'']]],
  ['uv_5finterface_5faddress_5fs_107',['uv_interface_address_s',['../structuv__interface__address__s.html',1,'']]],
  ['uv_5fkey_5ft_108',['uv_key_t',['../structuv__key__t.html',1,'']]],
  ['uv_5flib_5ft_109',['uv_lib_t',['../structuv__lib__t.html',1,'']]],
  ['uv_5floop_5fs_110',['uv_loop_s',['../structuv__loop__s.html',1,'']]],
  ['uv_5fmetrics_5fs_111',['uv_metrics_s',['../structuv__metrics__s.html',1,'']]],
  ['uv_5fonce_5fs_112',['uv_once_s',['../structuv__once__s.html',1,'']]],
  ['uv_5fpasswd_5fs_113',['uv_passwd_s',['../structuv__passwd__s.html',1,'']]],
  ['uv_5fpipe_5fs_114',['uv_pipe_s',['../structuv__pipe__s.html',1,'']]],
  ['uv_5fpoll_5fs_115',['uv_poll_s',['../structuv__poll__s.html',1,'']]],
  ['uv_5fprepare_5fs_116',['uv_prepare_s',['../structuv__prepare__s.html',1,'']]],
  ['uv_5fprocess_5foptions_5fs_117',['uv_process_options_s',['../structuv__process__options__s.html',1,'']]],
  ['uv_5fprocess_5fs_118',['uv_process_s',['../structuv__process__s.html',1,'']]],
  ['uv_5frandom_5fs_119',['uv_random_s',['../structuv__random__s.html',1,'']]],
  ['uv_5freq_5fs_120',['uv_req_s',['../structuv__req__s.html',1,'']]],
  ['uv_5frusage_5ft_121',['uv_rusage_t',['../structuv__rusage__t.html',1,'']]],
  ['uv_5frwlock_5ft_122',['uv_rwlock_t',['../structuv__rwlock__t.html',1,'']]],
  ['uv_5fshutdown_5fs_123',['uv_shutdown_s',['../structuv__shutdown__s.html',1,'']]],
  ['uv_5fsignal_5fs_124',['uv_signal_s',['../structuv__signal__s.html',1,'']]],
  ['uv_5fstat_5ft_125',['uv_stat_t',['../structuv__stat__t.html',1,'']]],
  ['uv_5fstatfs_5fs_126',['uv_statfs_s',['../structuv__statfs__s.html',1,'']]],
  ['uv_5fstdio_5fcontainer_5fs_127',['uv_stdio_container_s',['../structuv__stdio__container__s.html',1,'']]],
  ['uv_5fstream_5fs_128',['uv_stream_s',['../structuv__stream__s.html',1,'']]],
  ['uv_5ftcp_5fs_129',['uv_tcp_s',['../structuv__tcp__s.html',1,'']]],
  ['uv_5fthread_5foptions_5fs_130',['uv_thread_options_s',['../structuv__thread__options__s.html',1,'']]],
  ['uv_5ftimer_5fs_131',['uv_timer_s',['../structuv__timer__s.html',1,'']]],
  ['uv_5ftimespec64_5ft_132',['uv_timespec64_t',['../structuv__timespec64__t.html',1,'']]],
  ['uv_5ftimespec_5ft_133',['uv_timespec_t',['../structuv__timespec__t.html',1,'']]],
  ['uv_5ftimeval64_5ft_134',['uv_timeval64_t',['../structuv__timeval64__t.html',1,'']]],
  ['uv_5ftimeval_5ft_135',['uv_timeval_t',['../structuv__timeval__t.html',1,'']]],
  ['uv_5ftty_5fs_136',['uv_tty_s',['../structuv__tty__s.html',1,'']]],
  ['uv_5fudp_5fs_137',['uv_udp_s',['../structuv__udp__s.html',1,'']]],
  ['uv_5fudp_5fsend_5fs_138',['uv_udp_send_s',['../structuv__udp__send__s.html',1,'']]],
  ['uv_5futsname_5fs_139',['uv_utsname_s',['../structuv__utsname__s.html',1,'']]],
  ['uv_5fwork_5fs_140',['uv_work_s',['../structuv__work__s.html',1,'']]],
  ['uv_5fwrite_5fs_141',['uv_write_s',['../structuv__write__s.html',1,'']]]
];
